/* ═══════════════════════════════════════════════════════════
   OpenBanner — Starter Templates
   ═══════════════════════════════════════════════════════════ */

export function loadPresets() {
  return [
    {
      name: 'Social OG Card',
      icon: '🔗',
      width: 1200,
      height: 630,
      backgroundColor: '#0f0f1a',
      elements: [
        {
          type: 'rect',
          left: 0, top: 0,
          width: 1200, height: 630,
          color: 'rgba(15,15,26,1)',
          radius: 0,
        },
        {
          type: 'rect',
          left: 40, top: 40,
          width: 1120, height: 550,
          color: 'rgba(255,255,255,0.03)',
          radius: 24,
        },
        {
          type: 'text',
          text: 'Your Headline Goes Here',
          left: 80, top: 200,
          fontSize: 64,
          color: '#ffffff',
          fontWeight: 'bold',
          effect: 'none',
          maxWidth: 800,
        },
        {
          type: 'text',
          text: 'A compelling description that makes people want to click and learn more about what you have to share.',
          left: 80, top: 310,
          fontSize: 24,
          color: '#8b92b0',
          fontWeight: 'normal',
          effect: 'none',
          maxWidth: 700,
        },
        {
          type: 'text',
          text: 'yoursite.com',
          left: 80, top: 500,
          fontSize: 18,
          color: '#00e5ff',
          fontWeight: '500',
          effect: 'none',
        },
      ],
    },
    {
      name: 'YouTube Thumbnail',
      icon: '🎬',
      width: 1280,
      height: 720,
      backgroundColor: '#1a0a2e',
      elements: [
        {
          type: 'rect',
          left: 0, top: 480,
          width: 1280, height: 240,
          color: 'rgba(0,0,0,0.6)',
          radius: 0,
        },
        {
          type: 'text',
          text: 'WATCH THIS',
          left: 60, top: 520,
          fontSize: 80,
          color: '#ffffff',
          fontWeight: 'bold',
          effect: 'gradient',
        },
        {
          type: 'text',
          text: 'Something amazing happened!',
          left: 60, top: 630,
          fontSize: 32,
          color: '#e0e0e0',
          fontWeight: 'normal',
          effect: 'none',
        },
        {
          type: 'rect',
          left: 1060, top: 40,
          width: 180, height: 60,
          color: '#ff0000',
          radius: 30,
        },
        {
          type: 'text',
          text: 'NEW',
          left: 1115, top: 52,
          fontSize: 28,
          color: '#ffffff',
          fontWeight: 'bold',
          effect: 'none',
        },
      ],
    },
    {
      name: 'Twitter Header',
      icon: '🐦',
      width: 1500,
      height: 500,
      backgroundColor: '#0a1628',
      elements: [
        {
          type: 'rect',
          left: 0, top: 0,
          width: 1500, height: 500,
          color: '#0a1628',
          radius: 0,
        },
        {
          type: 'text',
          text: 'John Developer',
          left: 100, top: 140,
          fontSize: 72,
          color: '#ffffff',
          fontWeight: 'bold',
          effect: 'none',
        },
        {
          type: 'text',
          text: 'Building the future, one commit at a time.',
          left: 100, top: 240,
          fontSize: 28,
          color: '#8b92b0',
          fontWeight: 'normal',
          effect: 'none',
          maxWidth: 600,
        },
        {
          type: 'rect',
          left: 100, top: 320,
          width: 120, height: 4,
          color: '#00e5ff',
          radius: 2,
        },
        {
          type: 'text',
          text: '🚀 Open to work',
          left: 100, top: 360,
          fontSize: 22,
          color: '#00e5ff',
          fontWeight: '500',
          effect: 'none',
        },
      ],
    },
    {
      name: 'Instagram Post',
      icon: '📸',
      width: 1080,
      height: 1080,
      backgroundColor: '#1e1e24',
      elements: [
        {
          type: 'rect',
          left: 0, top: 0,
          width: 1080, height: 1080,
          color: '#1e1e24',
          radius: 0,
        },
        {
          type: 'text',
          text: 'QUOTE\nOF THE\nDAY',
          left: 80, top: 200,
          fontSize: 120,
          color: '#ffffff',
          fontWeight: 'bold',
          effect: 'gradient',
        },
        {
          type: 'rect',
          left: 80, top: 640,
          width: 920, height: 2,
          color: 'rgba(255,255,255,0.1)',
          radius: 1,
        },
        {
          type: 'text',
          text: '"Design is not just what it looks like. Design is how it works."',
          left: 80, top: 690,
          fontSize: 32,
          color: '#c0c0d0',
          fontWeight: 'normal',
          effect: 'none',
          maxWidth: 920,
        },
        {
          type: 'text',
          text: '— Steve Jobs',
          left: 80, top: 820,
          fontSize: 24,
          color: '#ff007f',
          fontWeight: '500',
          effect: 'none',
        },
        {
          type: 'text',
          text: '@yourhandle',
          left: 80, top: 980,
          fontSize: 20,
          color: '#5a6180',
          fontWeight: 'normal',
          effect: 'none',
        },
      ],
    },
    {
      name: 'LinkedIn Banner',
      icon: '💼',
      width: 1584,
      height: 396,
      backgroundColor: '#0a1628',
      elements: [
        {
          type: 'rect',
          left: 0, top: 0,
          width: 1584, height: 396,
          color: '#0a1628',
          radius: 0,
        },
        {
          type: 'text',
          text: 'Software Engineer',
          left: 120, top: 100,
          fontSize: 56,
          color: '#ffffff',
          fontWeight: 'bold',
          effect: 'none',
        },
        {
          type: 'text',
          text: 'Turning ideas into production-ready systems',
          left: 120, top: 180,
          fontSize: 24,
          color: '#8b92b0',
          fontWeight: 'normal',
          effect: 'none',
        },
        {
          type: 'rect',
          left: 120, top: 240,
          width: 80, height: 3,
          color: '#00e5ff',
          radius: 2,
        },
        {
          type: 'text',
          text: 'Node.js  •  React  •  DevOps  •  Cloud',
          left: 120, top: 275,
          fontSize: 18,
          color: '#00e5ff',
          fontWeight: '500',
          effect: 'none',
        },
      ],
    },
    {
      name: 'Neon Ad Banner',
      icon: '✨',
      width: 728,
      height: 90,
      backgroundColor: '#0a0014',
      elements: [
        {
          type: 'rect',
          left: 0, top: 0,
          width: 728, height: 90,
          color: '#0a0014',
          radius: 0,
        },
        {
          type: 'text',
          text: 'SPECIAL OFFER',
          left: 30, top: 18,
          fontSize: 36,
          color: '#ffffff',
          fontWeight: 'bold',
          effect: 'neon',
        },
        {
          type: 'text',
          text: 'Get 50% off — Limited time only!',
          left: 360, top: 30,
          fontSize: 22,
          color: '#c0c0d0',
          fontWeight: 'normal',
          effect: 'none',
        },
        {
          type: 'rect',
          left: 610, top: 22,
          width: 100, height: 44,
          color: '#ff007f',
          radius: 22,
        },
        {
          type: 'text',
          text: 'Shop →',
          left: 626, top: 30,
          fontSize: 20,
          color: '#ffffff',
          fontWeight: 'bold',
          effect: 'none',
        },
      ],
    },
    {
      name: 'Gradient Hero',
      icon: '🌈',
      width: 1920,
      height: 1080,
      backgroundColor: '#0f0c29',
      elements: [
        {
          type: 'rect',
          left: 0, top: 0,
          width: 1920, height: 1080,
          color: '#0f0c29',
          radius: 0,
        },
        {
          type: 'text',
          text: 'BUILD\nSOMETHING\nAMAZING',
          left: 120, top: 280,
          fontSize: 120,
          color: '#ffffff',
          fontWeight: 'bold',
          effect: 'gradient',
        },
        {
          type: 'rect',
          left: 120, top: 720,
          width: 240, height: 64,
          color: '#7f00ff',
          radius: 32,
        },
        {
          type: 'text',
          text: 'Get Started',
          left: 172, top: 732,
          fontSize: 26,
          color: '#ffffff',
          fontWeight: '600',
          effect: 'none',
        },
        {
          type: 'text',
          text: 'The platform for modern teams',
          left: 400, top: 738,
          fontSize: 22,
          color: '#8b92b0',
          fontWeight: 'normal',
          effect: 'none',
        },
      ],
    },
    {
      name: 'Minimal Blog',
      icon: '📝',
      width: 1200,
      height: 630,
      backgroundColor: '#fafafa',
      elements: [
        {
          type: 'rect',
          left: 0, top: 0,
          width: 1200, height: 630,
          color: '#fafafa',
          radius: 0,
        },
        {
          type: 'rect',
          left: 0, top: 0,
          width: 8, height: 630,
          color: '#ff007f',
          radius: 0,
        },
        {
          type: 'text',
          text: 'How to Build a Banner API',
          left: 80, top: 200,
          fontSize: 56,
          color: '#1a1a2e',
          fontWeight: 'bold',
          effect: 'none',
          maxWidth: 900,
        },
        {
          type: 'text',
          text: 'A deep dive into self-hosted image rendering with Puppeteer, Express, and Docker.',
          left: 80, top: 310,
          fontSize: 24,
          color: '#666680',
          fontWeight: 'normal',
          effect: 'none',
          maxWidth: 800,
        },
        {
          type: 'text',
          text: 'June 2026  •  8 min read',
          left: 80, top: 500,
          fontSize: 16,
          color: '#999',
          fontWeight: 'normal',
          effect: 'none',
        },
      ],
    },
  ];
}
